name: Build and Deploy to ECR

permissions:
  contents: read

on:
  push:
    branches: ['main']
  workflow_dispatch:

env:
  ECR_REGISTRY: 425927917438.dkr.ecr.ap-southeast-2.amazonaws.com
  IMAGE_NAME: backendecr
  AWS_REGION: ap-southeast-2
  ECS_CLUSTER: backend
  ECS_SERVICE: backend
  
jobs:
  buildImage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
              
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1 
            
      - name: Build and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          CONNECTION_S: ${{ secrets.CONNECTION_STRING }}
          OPENAI_A: ${{ secrets.OPENAI_APIKEY2 }}
          STRIPE_S: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_W_S: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        run: |
          docker build \
                -t $ECR_REGISTRY/$IMAGE_NAME:latest \
                -t $ECR_REGISTRY/$IMAGE_NAME:${{ github.sha }} \
                --build-arg CONNECTION=$CONNECTION_S \
                --build-arg STRIPE=$STRIPE_S \
                --build-arg STRIPE_W=$STRIPE_W_S \
                --build-arg OPENAI=$OPENAI_A \
                .     
          docker push $ECR_REGISTRY/$IMAGE_NAME

      - name: Update ECS task
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment
